# Akcja odpowiada za zdeployowania aplikacji na środowisko testowe
name: Deploy PR to Testing Environment

# Akcja uruchamia się w momencie utworzenia pull requestu do brancha 'master'
on:
  pull_request:
    branches:
    - master

# Zapewnia ochrone przed konfliktem pomiędzy tą akcją, a akcją usuwającą środowisko testowe
concurrency: ci-${{ github.event.number }}

# Ustawienie zmiennych środowiskowych wykorzystywanych podczas wykonywania akcji
env:
  WEBAPP_NAME: AGH-mdtest
  RESOURCE_GROUP: AGH-md-test
  SLOT_NAME: pr-${{ github.event.number }}
  AZURE_WEBAPP_PACKAGE_PATH: './publish'

# Permisje potrzebne do zalogowania do Azure przy pomocy Federated Credentials
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: false

# Budowanie aplikacji
    - name: Build with Dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release

# Uruchomienie testów jednostkowych
    - name: Run Unit Tests
      run: dotnet test ./tests/UnitTests/UnitTests.csproj --configuration Release

# Uruchomienie testów funkcjonalnych
    - name: Run Functional Tests
      run: dotnet test ./tests/FunctionalTests/FunctionalTests.csproj --configuration Release

# Opublikowanie paczki z aplikacją
    - name: Publish Build Artifacts
      run: dotnet publish ./src/Web/Web.csproj -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/eShopOnWeb

# Upload paczki z aplikacją w celu pobrania jej w następnym kroku z deploymentem
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: eShopOnWeb
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/eShopOnWeb
     
  set-up-test-env:
    name: Create testing environment
    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure
      uses: Azure/login@v2
      with:
        client-id: ${{ secrets.WEB_APP_CLIENT_ID }}
        tenant-id: ${{ secrets.WEB_APP_DIRECTORY_ID }}
        subscription-id: ${{ secrets.WEB_APP_SUBSCRIPTION_ID }} 
        enable-AzPSSession: true

# Stworzenie testowego deployment slotu. Nazwa odpowiada numerowi pull requestu, który jest unikalny
    - name: Create slot for testing purposes
      run: az webapp deployment slot create --resource-group $RESOURCE_GROUP  --name $WEBAPP_NAME --slot $SLOT_NAME

# Ustawienie zmiennej środowiskowej odpowiadającej środowisku testowemu
    - name: Set Envrionment Variable
      uses: azure/appservice-settings@v1
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        mask-inputs: false
        slot-name: ${{ env.SLOT_NAME }}
        app-settings-json: '[{ "name": "ASPNETCORE_ENVIRONMENT", "value": "Development", "slotSetting": true }]'

  deploy:
    name: Deploy to testing environment env
    runs-on: ubuntu-latest
    needs: [build, set-up-test-env]
    permissions:
      pull-requests: write
      id-token: write
      contents: read

# Pobranie zuploadowanej wcześniej paczki z aplikacją
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: eShopOnWeb

# Zalogowanie do Azure przy użyciu Federated Credentials
    - name: Login to Azure
      uses: Azure/login@v2
      with:
        client-id: ${{ secrets.WEB_APP_CLIENT_ID }}
        tenant-id: ${{ secrets.WEB_APP_DIRECTORY_ID }}
        subscription-id: ${{ secrets.WEB_APP_SUBSCRIPTION_ID }} 
        enable-AzPSSession: true

# Wdrożenie aplikacji na uprzednio stworzone środowisko testowe
    - name: Deploy to testing environment
      uses: azure/webapps-deploy@v3
      id: deploy-to-test
      with: 
        app-name: ${{ env.WEBAPP_NAME }}
        slot-name:  ${{ env.SLOT_NAME }}
        package: '.'

#  Wrzucenie linku z adresem URL aplikacji do pull requestu
    - name: Comment on PR with the preview link
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          ## Preview link: https://${{ env.WEBAPP_NAME }}-${{env.SLOT_NAME }}.azurewebsites.net 
          
          - Your changes have been deployed to the preview site. The preview site will update as you add more commits to this branch.
          - The preview link is shareable, but will be deleted when the pull request is merged or closed.

          > *This is an automated message.*
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
   
